tests/netpipe: run 5.1.4 version netpipe
Since the structure of netpipe has changed, its running command
also changed. Thus we need to accordingly changing tests/netpipe.

Also, for modules in netpipe, it runs right after compiling, we can
also imitate this, do 'make tcp' in tests/netpipe, instead of
pkg/netpipe/PKGBUILD. Additionally, 'make' with no parameter equals
to 'make mpi', thus we can't just run 'make' for all the modules.

== before [1] ==
/NetPIPE-3.7.2$ ls
bin  dox  hosts  makefile  src

Compile NetPIPE using 'make tcp'

remote_host> NPtcp [options]
local_host>  NPtcp -h remote_host [options]
                       OR
local_host>  nplaunch NPtcp -h remote_host [options]

== now [2] ==
/NetPIPE-5.1.4$ ls
dox  makefile  MP_Lite  npplot  sb.disk  sb.diskread  sb.mpi-4.0.1  sb.np  src

make tcp
mpirun -np 2 --hostfile mpihosts.2 NPtcp --bidir

make mpi
mpirun -np 2 --hostfile np.hosts NPmpi  -o np.mpi.qdr

==============
MPI module shows the basic function of netpipe, thus here we choose
to use it to let netpipe normally run in lkp. As for TCP module, I
didn't find proper parameter for now, thus comment out it.

/result/netpipe/cs-localhost-performance-mpi-ucode=0x42e/lkp-ivb-2ep1/debian-11.1-x86_64-20220510.cgz/x86_64-rhel-8.3/gcc-11/3d7cb6b04c3f3115719235cc6866b10326de34cd/5$ /lkp/carel/src/stats/netpipe < netpipe
less_8K_usec.avg: 0.14820796721311474
bigger_5M_Mbps.avg: 66.46866666666666

Link: [1] https://github.com/ix-project/netpipe/blob/master/dox/README
Link: [2] https://web.archive.org/web/20201020125230/http://netpipe.cs.ksu.edu/download/README.NetPIPE
Signed-off-by: Carel Si <beibei.si@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/netpipe b/tests/netpipe
--- a/tests/netpipe
+++ b/tests/netpipe
@@ -5,12 +5,17 @@
 ## the best of ttcp and netperf and visually represents the network
 ## performance under a variety of conditions.
 
+cd $BENCHMARK_ROOT/netpipe || die "no $BENCHMARK_ROOT/netpipe"
+
 [ -n "$direct_server_ips" ] && server=$direct_server_ips
 [ -z "$server" ] && server=127.0.0.1
 server=${server%% *}
 
+log_cmd make CFLAGS="-fcommon" $test || die "failed to compile $test"
+
 case $test in
-tcp )
-	log_cmd NPtcp -n 1000 -h $server 2>&1
+mpi )
+	echo "$server slots=1" > mpihost
+	log_cmd mpirun -np 1 --hostfile mpihost --allow-run-as-root NPmpi --repeats 1000 2>&1
 	;;
 esac
