stats/rcuscale: return skip if module argument is invalid
There's no tasks-tracing for rcuscale in old kernel:
----------
modprobe: ERROR: could not insert 'rcuscale': Invalid argument
----------

Signed-off-by: Chen Rong <rong.a.chen@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/rcuscale b/tests/rcuscale
--- a/tests/rcuscale
+++ b/tests/rcuscale
@@ -11,8 +11,13 @@
 args=""
 [ -n "$scale_type" ] && args="$args scale_type=$scale_type"
 
-log_cmd modprobe rcuscale $args ||
-die "failed to load rcuscale module, try to enable CONFIG_RCU_SCALE_TEST as module and build rcuscale.ko"
+log=$(log_cmd modprobe rcuscale $args 2>&1) || {
+	echo "$log"
+	echo "$log" | grep -q "Invalid argument" ||
+	die "failed to load rcuscale module, try to enable CONFIG_RCU_SCALE_TEST as module and build rcuscale.ko"
+	echo "rcu-scale: Skip"
+	exit
+}
 
 log_cmd sleep $runtime
 
