shellcheck: cleanup SC2115 offenses
SC2115: Use "${var:?}" to ensure this never expands to / .

Link: https://github.com/koalaman/shellcheck/wiki/SC2115
Signed-off-by: Yujie Liu <yujie.liu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/sbin/makepkg b/sbin/makepkg
--- a/sbin/makepkg
+++ b/sbin/makepkg
@@ -3872,7 +3872,10 @@ elif (( !REPKG )); then
 
 	if (( CLEANBUILD )); then
 		msg "$(gettext "Removing existing %s directory...")" "\$srcdir/"
-		rm -rf "$srcdir"/*
+		rm -rf "${srcdir:?}"/* || {
+			error "$(gettext "rm -rf $srcdir/* failed")"
+			exit 1
+		}
 	fi
 
 	extract_sources
