lkp install: remove standalone validate_parameters()
To consolidate the code.

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>

diff --git a/lkp-exec/install b/lkp-exec/install
--- a/lkp-exec/install
+++ b/lkp-exec/install
@@ -65,30 +65,19 @@ do
 	shift
 done
 
-validate_parameters()
+check_yaml_file()
 {
-    local ret=0
-    for filename in "$@"
-    do
-        if [ -x "$filename" ]; then
-            continue
-        elif [ ${filename##*.} = "yaml" ]; then
-            if [ -f $filename ]; then
-                grep -q '^arch: ' $filename || {
-                    echo "only atomic jobs can be installed" >&2
-                    echo "Please run lkp split-job $filename first" >&2
-                    ret=1
-                }
-            else
-                echo "$0: cannot find file $filename" >&2
-                ret=1
-            fi
-        else
-            echo "$0: skip unknown parameter $filename" >&2
-            ret=1
-        fi
-    done
-    return $ret
+	local filename=$1
+	if [ -f $filename ]; then
+		grep -q '^arch: ' $filename || {
+			echo "only atomic jobs can be installed" >&2
+			echo "Please run lkp split-job $filename first" >&2
+			exit 1
+		}
+	else
+		echo "$0: cannot find file $filename" >&2
+		exit 1
+	fi
 }
 
 make_wakeup() {
@@ -268,8 +257,6 @@ export DISTRO
 
 export LKP_LOCAL_RUN=1
 
-validate_parameters "$@" || exit 1
-
 if [[ -z "$1" ]]; then
 	install_base_support
 	all_scripts='lkp makepkg'
@@ -282,8 +269,12 @@ do
 	if [ -x "$filename" ]; then
 		all_scripts+=" $(basename $filename) "
 	elif [ ${filename##*.} = "yaml" ]; then
+		check_yaml_file $filename
 		parse_yaml $filename
 		all_scripts+=" $scripts "
+        else
+            echo "$0: skip unknown parameter $filename" >&2
+            exit 1
 	fi
 done
 
