lkp install: support new PKGBUILD layout
Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>

diff --git a/lkp-exec/install b/lkp-exec/install
--- a/lkp-exec/install
+++ b/lkp-exec/install
@@ -163,14 +163,26 @@ bundle_install_china() {
 makepkg_install() {
 	local pkg=$1
 	local force_opt=
+	local path="$LKP_SRC/pkg/$pkg/PKGBUILD"
 
 	[ -n "$FORCE_MODE" ] && force_opt="-f"
-	if [ -d "$LKP_SRC/pkg/$pkg" ]; then
+
+	[ -f "$path" ] || path=$LKP_SRC/programs/$pkg/PKGBUILD
+	[ -f "$path" ] || path=$LKP_SRC/monitors/$pkg/PKGBUILD
+	[ -f "$path" ] || path=$LKP_SRC/programs/*/PKGBUILD-$pkg
+	[ -f "$path" ] || path=$LKP_SRC/monitors/*/PKGBUILD-$pkg
+	[ -f "$path" ] || {
+		echo "Failed to find PKGBUILD path for $pkg"
+		return 1
+	}
+
+	if [ -f "$path" ]; then
 		(
-			cd "$LKP_SRC/pkg/$pkg" || exit
-			echo "Building package with: $LKP_SRC/pkg/$pkg/PKGBUILD"
+			cd "$(dirname $path)" || exit
+			echo "Building package with: $path"
 			PACMAN="$LKP_SRC/sbin/pacman-LKP" CARCH=$arch BUILDDIR="$HOME/.cache/lkp-tests/pkg-builddir" \
-			"$LKP_SRC/sbin/makepkg" --config "$(lkp_src)/etc/makepkg.conf" -s -i --skippgpcheck "$force_opt"
+			"$LKP_SRC/sbin/makepkg" --config "$(lkp_src)/etc/makepkg.conf" -s -i --skippgpcheck "$force_opt" \
+			-p $(basename $path)
 		)
 	else
 		return 0
