distro/debian: handle the case that apt install fails the first time
Signed-off-by: Yujie Liu <yujie.liu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/distro/debian b/distro/debian
--- a/distro/debian
+++ b/distro/debian
@@ -203,6 +203,10 @@ distro_install_depends()
 		echo install packages for $script: $packages
 
 		do_apt_install
+
+		# some apt mirrors may have issue and fail in the first time of apt install
+		# so try for a second time if the first time fails
+		[[ $? -ne 0 ]] && do_apt_install
 	done
 }
 
